### ISSUE TITLE
Remove A2 Online Judge as it is no longer supported

### ISSUE THREAD

**Issue by Aman-Codes** [Aman-Codes/pennamechooser#1]
**Describe the bug**
Remove the A2 Online Judge Code as it is no longer maintained. Remove the API code from backend and update the frontend accordingly.

**To Reproduce**
Enter any username and hit enter. The A2 Online Judge API always fails as the webpage does not exists.

**Expected behavior**
All the APIs displayed should be working properly.

**Screenshots**
![image](https://user-images.githubusercontent.com/54680709/193418852-abae44d0-e84f-4367-99c4-6826f461ec9e.png)

**Comment by retry19** [comment]
can I contribute on this issue?

**Comment by ManavMalhotra** [comment]
Assign this task to me

**Comment by Aman-Codes** [comment]
Hi @retry19 are you still working on it? If not then we could assign it to @ManavMalhotra

**Comment by ManavMalhotra** [comment]
You can assign it to me
