### ISSUE TITLE
Fix the Pinterest API

### ISSUE THREAD

**Issue by Aman-Codes** [Aman-Codes/pennamechooser#4]
**Describe the bug**
Fix the Pinterest API as it always shows penname is no longer available even if it is available. Update the backend API code accordingly.

**To Reproduce**
Enter any username and hit enter. The Pinterest API always fails.

**Expected behavior**
All the APIs displayed should be working properly.

**Screenshots**
![image](https://user-images.githubusercontent.com/54680709/193418852-abae44d0-e84f-4367-99c4-6826f461ec9e.png)

**Comment by drishit96** [comment]
Hi @Aman-Codes, I'd like to work on this issue

**Comment by drishit96** [comment]
@Aman-Codes, I just hit the pinterest url that is used in the project and it always returns 200 OK, **even for usernames that exist**. I think we need to find a different way to know if a username exists or not.
